-- ============================================
-- ✅ PostgreSQL Schema for Auction Management System
-- ============================================

CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" VARCHAR(50) UNIQUE NOT NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "email" VARCHAR(100) UNIQUE NOT NULL,
  "phone" VARCHAR(20),
  "role_id" INT,
  "balance" DECIMAL(18,2) DEFAULT 0,
  "status" VARCHAR(20),
  "avatar_url" VARCHAR(255),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "AccountTransaction" (
  "trans_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "amount" DECIMAL(18,2),
  "type" VARCHAR(20),
  "status" VARCHAR(20),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Product" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" INT,
  "name" VARCHAR(100),
  "categories" VARCHAR(50),
  "description" TEXT,
  "start_price" DECIMAL(18,2),
  "estimate_price" VARCHAR(100),
  "deposit" DECIMAL(18,2),
  "image_url" VARCHAR(255),
  "status" VARCHAR(20),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Auction" (
  "auction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT,
  "start_time" TIMESTAMP,
  "end_time" TIMESTAMP,
  "status" VARCHAR(20),
  "highest_current_price" DECIMAL(18,2),
  "bid_step_amount" VARCHAR(50),
  "winner_id" INT
);

CREATE TABLE "Bid" (
  "bid_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" INT,
  "bidder_id" INT,
  "bid_amount" DECIMAL(18,2),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "max_autobid_amount" DECIMAL(18,2),
  "step_autobid_amount" DECIMAL(18,2),
  "is_auto" BOOLEAN DEFAULT FALSE,
  "is_highest" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "Notification" (
  "noti_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT,
  "message" TEXT,
  "type" VARCHAR(50),
  "is_read" BOOLEAN DEFAULT FALSE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" INT,
  "user_id" INT,
  "rating" INT,
  "comment" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "TransactionAfterAuction" (
  "txn_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" INT,
  "seller_id" INT,
  "buyer_id" INT,
  "amount" DECIMAL(18,2),
  "status" VARCHAR(20),
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "AdminLog" (
  "log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" INT,
  "action" TEXT,
  "ip_address" VARCHAR(50),
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Image" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT,
  "image_url" VARCHAR(255),
  "is_thumbnail" BOOLEAN DEFAULT FALSE
);

CREATE TABLE "Role" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" VARCHAR(200) UNIQUE NOT NULL,
  "description" VARCHAR(500)
);

CREATE TABLE "Permission" (
  "permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "permission_name" VARCHAR(200) UNIQUE NOT NULL,
  "description" VARCHAR(500)
);

CREATE TABLE "RolePermission" (
  "role_id" INT,
  "permission_id" INT,
  PRIMARY KEY ("role_id", "permission_id")
);

-- ============================
-- 🔗 Foreign Keys
-- ============================

ALTER TABLE "User"
  ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("role_id");

ALTER TABLE "AccountTransaction"
  ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Product"
  ADD FOREIGN KEY ("seller_id") REFERENCES "User" ("user_id");

ALTER TABLE "Auction"
  ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "Auction"
  ADD FOREIGN KEY ("winner_id") REFERENCES "User" ("user_id");

ALTER TABLE "Bid"
  ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "Bid"
  ADD FOREIGN KEY ("bidder_id") REFERENCES "User" ("user_id");

ALTER TABLE "Notification"
  ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Feedback"
  ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "Feedback"
  ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "TransactionAfterAuction"
  ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "TransactionAfterAuction"
  ADD FOREIGN KEY ("seller_id") REFERENCES "User" ("user_id");

ALTER TABLE "TransactionAfterAuction"
  ADD FOREIGN KEY ("buyer_id") REFERENCES "User" ("user_id");

ALTER TABLE "AdminLog"
  ADD FOREIGN KEY ("admin_id") REFERENCES "User" ("user_id");

ALTER TABLE "Image"
  ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "RolePermission"
  ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("role_id");

ALTER TABLE "RolePermission"
  ADD FOREIGN KEY ("permission_id") REFERENCES "Permission" ("permission_id");
