CREATE TABLE "User" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "phone" varchar(20),
  "role_id" int,
  "balance" decimal(18,2) DEFAULT 0,
  "status" varchar(20),
  "created_at" datetime
);

CREATE TABLE "AccountTransaction" (
  "trans_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "amount" decimal(18,2),
  "type" varchar(20),
  "status" varchar(20),
  "created_at" datetime
);

CREATE TABLE "Product" (
  "product_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id" int,
  "name" varchar(100),
  "categories" varchar(50),
  "description" text,
  "start_price" decimal(18,2),
  "estimate_price" varchar(100),
  "deposit" decimal(18,2),
  "image_url" varchar(255),
  "status" varchar(20),
  "created_at" datetime
);

CREATE TABLE "Auction" (
  "auction_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "start_time" datetime,
  "end_time" datetime,
  "status" varchar(20),
  "highest_current_price" int,
  "bid_step_amount" string,
  "winner_id" int
);

CREATE TABLE "Bid" (
  "bid_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" int,
  "bidder_id" int,
  "bid_amount" decimal(18,2),
  "created_at" datetime,
  "max_autobid_amount" decimal(18,2),
  "step_autobid_amount" decimal(18,2),
  "is_auto" boolean,
  "is_highest" boolean
);

CREATE TABLE "Notification" (
  "noti_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "message" text,
  "type" varchar(50),
  "is_read" boolean DEFAULT false,
  "created_at" datetime
);

CREATE TABLE "Feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" int,
  "user_id" int,
  "rating" int,
  "comment" text,
  "created_at" datetime
);

CREATE TABLE "TransactionAfterAuction" (
  "txn_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auction_id" int,
  "seller_id" int,
  "buyer_id" int,
  "amount" decimal(18,2),
  "status" varchar(20),
  "updated_at" datetime
);

CREATE TABLE "AdminLog" (
  "log_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_id" int,
  "action" text,
  "ip_address" varchar(50),
  "created_at" datetime
);

CREATE TABLE "Image" (
  "image_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "image_url" varchar[255],
  "is_thumnail" boolean
);

CREATE TABLE "Role" (
  "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" varchar(200) UNIQUE NOT NULL,
  "description" varchar(500)
);

CREATE TABLE "Permission" (
  "permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "permission_name" varchar(200) UNIQUE NOT NULL,
  "description" varchar(500)
);

CREATE TABLE "RolePermission" (
  "role_id" int,
  "permission_id" int,
  "primary" key(role_id,permission_id)
);

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("role_id");

ALTER TABLE "AccountTransaction" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Product" ADD FOREIGN KEY ("seller_id") REFERENCES "User" ("user_id");

ALTER TABLE "Auction" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "Auction" ADD FOREIGN KEY ("winner_id") REFERENCES "User" ("user_id");

ALTER TABLE "Bid" ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "Bid" ADD FOREIGN KEY ("bidder_id") REFERENCES "User" ("user_id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("user_id");

ALTER TABLE "TransactionAfterAuction" ADD FOREIGN KEY ("auction_id") REFERENCES "Auction" ("auction_id");

ALTER TABLE "TransactionAfterAuction" ADD FOREIGN KEY ("seller_id") REFERENCES "User" ("user_id");

ALTER TABLE "TransactionAfterAuction" ADD FOREIGN KEY ("buyer_id") REFERENCES "User" ("user_id");

ALTER TABLE "AdminLog" ADD FOREIGN KEY ("admin_id") REFERENCES "User" ("user_id");

ALTER TABLE "Image" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "RolePermission" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("role_id");

ALTER TABLE "RolePermission" ADD FOREIGN KEY ("permission_id") REFERENCES "Permission" ("permission_id");
